//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaVendas.Context
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Tb_Empresa
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tb_Empresa()
        {
            this.Tb_SegmentoEmpresa = new HashSet<Tb_SegmentoEmpresa>();
            this.Tb_Vendas = new HashSet<Tb_Vendas>();
        }
    
        public long IdEmpresa { get; set; }
        [Required(ErrorMessage = "Usuário é obrigatório!")]
        public long IdUsuarioCadastro { get; set; }
        [Required(ErrorMessage = "Razão Social é obrigatória!")]
        public string RazaoSocial { get; set; }
        [Required(ErrorMessage = "CNPJ é obrigatório!")]
        public string Cnpj { get; set; }
        [Required(ErrorMessage = "Endereço é obrigatório!")]
        public string Endereco { get; set; }
        [Required(ErrorMessage = "Telefone é obrigatório!")]
        public string Telefone { get; set; }
    
        public virtual Tb_Usuario Tb_Usuario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tb_SegmentoEmpresa> Tb_SegmentoEmpresa { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tb_Vendas> Tb_Vendas { get; set; }
    }
}
