//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaVendas.Context
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Tb_SegmentoEmpresa
    {
        public long IdSegmentoEmpresa { get; set; }
        [Required(ErrorMessage = "Empresa é obrigatória!")]
        public long IdEmpresa { get; set; }
        [Required(ErrorMessage = "Descrição do segmento é obrigatório!")]
        public string DesSegmento { get; set; }
        public bool Ativo { get; set; }
    
        public virtual Tb_Empresa Tb_Empresa { get; set; }
    }
}
