//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaVendas.Context
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Tb_Vendas
    {
        public long IdVenda { get; set; }
        [Required(ErrorMessage = "Empresa é obrigatória!")]
        public long IdEmpresa { get; set; }
        [Required(ErrorMessage = "Usuário é obrigatório!")]
        public long IdUsuarioCadastro { get; set; }
        [Required(ErrorMessage = "Valor é obrigatório!")]
        [DataType(DataType.Currency)]
        public decimal ValorVenda { get; set; }
        public System.DateTime DataVenda { get; set; }
        public bool EmitidoNF { get; set; }
    
        public virtual Tb_Empresa Tb_Empresa { get; set; }
        public virtual Tb_Usuario Tb_Usuario { get; set; }

        public Tb_Vendas()
        {
            this.DataVenda = DateTime.Now;
        }
    }
}
